### PR TITLE
Remove debug statement

### PR DESCRIPTION
**Pull request by chocolateboy**
<table>
<tr><th align="left">babel-plugin-transform-builtin-classes
</th><td>0.4.0</td></tr>
<tr><th  align="left">node</th><td>v8.9.3, v9.2.1</td></tr>
<tr><th  align="left">OS</th><td>Linux (Arch)</td></tr>
</table>

### test.js

```javascript
class Test extends Array {}
```

### .babelrc

```json
{
    "presets": ["es2015"],
    "plugins": [
        ["babel-plugin-transform-builtin-classes", { "globals": ["Array"] }]
    ]
}

```

### test
```sh
$ babel test.js > temp.js
$ node ./temp.js
```

### output
```
temp.js:1
(function (exports, require, module, __filename, __dirname) {  ✔ builtin extends patched
                                                               ^

SyntaxError: Invalid or unexpected token
```

### CODE REVIEW

**Comment by WebReflection** [comment]
good point ... however, the info was there for a reason ... do you mind changing it to:

```js
if (name && process.argv.some(a => /^-v|--verbose$/.test(a))) console.info('...')
```

so that it's posible to have the same output as before ?

**Comment by chocolateboy** [comment]
Why is it there (and why would process be defined)?

**Comment by WebReflection** [comment]
is there for visual feedback, and `process` is always defined in `node` ?

**Comment by chocolateboy** [comment]
Doesn't babel run in the browser with a `<script>` tag? e.g. https://www.npmjs.com/package/babel-transform-in-browser

Who is the visual feedback for? Surely it's more important that the plugin works?

**Comment by chocolateboy** [comment]
From my experience so far, it's pretty clear the plugin works (without this message) :-)

**Comment by WebReflection** [comment]
on the browser, there is no issue with current code because `console.info` will just print info in the console.

> Who is the visual feedback for?

developers. The plugin requires manual adjustment, it's easy to copy and paste a `.babelrc` and never patch the desired class. It happened to me already twice.

> Surely it's more important that the plugin works?

the plugin works already if you use `--out` info via `babel-cli`.

if the issue is `process` then:

```js
if (
  name &&
  typeof process === 'object' &&
  process.argv.some(a => /^-v|--verbose$/.test(a))
) console.info('...')
```

it's tooling, there's no need to save bytes here but I want to save my visual helper.

**Comment by chocolateboy** [comment]
> it's easy to copy and paste a `.babelrc` and never patch the desired class.

Surely this is caught by tests?

At any rate, thanks for explaining your rationale. I can understand why that might be useful to you personally, but:

* I have no use for it
* it results in broken code
* and it requires users of the plugin to somehow discover this issue to work around it

I'll stick with my fork for now and look forward to your (excellent) work being [integrated in Babel](https://github.com/babel/babel/issues/4480#issuecomment-350963150).

Feel free to close this PR if you don't plan to remove the message.

**Comment by WebReflection** [comment]
> it results in broken code

no, it doesn't. I've proposed an opt in, not an opt out. If you opt in, you know what you are doing.

> it requires users of the plugin to somehow discover this issue to work around it

there is no issue. It's an opt in that can be documented as such

**Comment by chocolateboy** [comment]
FYI:

```shell
$ babel --version
$ 6.26.0 (babel-core 6.26.0)

$ babel --verbose test.js > temp.js
error: unknown option `--verbose'

$ babel -v test.js > temp.js
error: unknown option `-v'
```

**Comment by WebReflection** [comment]
latest versions should work for everyone, described in here:
https://github.com/WebReflection/babel-plugin-transform-builtin-classes#about-logifpatched-option

**Comment by chocolateboy** [comment]
Thanks.

> Please note if you are piping babel output directly the log will interfere with the produced output.

There's no need for the messages to interfere with the generated output if they're logged to stderr e.g. via `console.warn` or `process.stderr.write`.

**Comment by WebReflection** [comment]
~~wouldn't that make the eventual build step fail?~~ nope, checked

it also feels weird to warn or err something that is actually an *info*

**Comment by WebReflection** [comment]
OK, `0.6.1` uses `warn` so everyone should be very happy now

**Pull request closed without merging**
